name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
      pull-requests: write # Read needed for nx affected, write for changesets
      repository-projects: read # Needed to set shas for Nx affected
      deployments: read # Needed to set shas for Nx affected
      actions: read # Needed to set shas for Nx affected
      issues: read
      statuses: write # For changesets
    runs-on: sh-codebuild
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # needed to allow nx affected to work
      - name: Install Dependencies
        run: npm ci
      # We cannot set this in the repo, because pnpm locally chokes on unset variables
      # https://github.com/pnpm/pnpm/issues/4393
      - name: Add NPM auth to .npmrc
        run: echo -e "\n//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> "${HOME}/.npmrc"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        with:
          publish: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
